site_name: CA Prediction Docs

theme:
  name: "material"
  palette:
    primary: deep purple
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.top
    # - navigation.sections
    - search.highlight
    - navigation.footer
  icon:
    repo: fontawesome/brands/git-alt

copyright: Copyright &copy; 2022 - 2023 Ezequiel González

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ezegonmac
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ezequiel-gonzalez-macho-329583223/

repo_url: https://github.com/ezegonmac/TFG-CellularAutomata
repo_name: ezegonmac/TFG-CellularAutomata

plugins:
  - mkdocstrings
  - search

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - API Reference: reference.md
  - Explanation: explanation.md
